name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  token:
    description: 'GitHub Token'
    required: true
  args:
    description: 'Who to greet'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Call Another Action'
      id: js_action
      uses: kengo-k/docker-build/internal/get@main
      with:
        token: ${{ inputs.token }}
        args: ${{ inputs.args }}

    - name: checkout latest commit
      uses: actions/checkout@v2

    - name: 'Display Output'
      shell: bash
      run: |
        output_array='${{ steps.js_action.outputs.docker_command }}'
        echo "$output_array" | jq -c '.[]' | while read -r element; do
          path=$(echo "$element" | jq -r '.path')
          name=$(echo "$element" | jq -r '.name')
          tag=$(echo "$element" | jq -r '.tag')
          echo "path: $path, name: $name, tag: $tag"
          docker build -t ghcr.io/${{ github.actor }}/$name:$tag -f $path $(dirname $path)
        done
