name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  token:
    description: 'GitHub Token'
    required: true
  args:
    description: 'Who to greet'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Call Another Action'
      id: js_action
      uses: kengo-k/docker-build/internal/get@main
      with:
        token: ${{ inputs.token }}
        args: ${{ inputs.args }}

    - name: 'Display Output'
      shell: bash
      run: echo "Output from JS Action: ${{ steps.js_action.outputs.docker_command }}"
