name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  token:
    description: 'GitHub Token'
    required: true
  args:
    description: 'Who to greet'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Call Another Action'
      uses: kengo-k/docker-build/internal/get@main
      with:
        token: ${{ inputs.token }}
        args: ${{ inputs.args }}
