name: 'get'
description: 'Get information for building Docker images'
inputs:
  token:
    description: 'GitHub Token'
    required: true
  timezone:
    description: 'Timezone for creating timestamps to include in image tag'
    required: true
    default: 'UTC'
  args:
    description: 'Configuration values for building images'
    required: true
outputs:
  build_args:
    description: 'Arguments to pass to the docker build command'
runs:
  using: 'docker'
  image: 'Dockerfile'
