name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  token:
    description: 'GitHub Token'
    required: true
  timezone:
    description: 'Timezone'
    required: true
    default: 'UTC'
  args:
    description: 'Who to greet'
    required: true
outputs:
  docker_command:
    description: 'The generated docker command'
runs:
  using: 'docker'
  image: 'Dockerfile'
