name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  token:
    description: 'GitHub Token'
    required: true
  args:
    description: 'Who to greet'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
