name: 'test to publish docker image'

on:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: 'test'
        uses: kengo-k/docker-build@main
        with:
          token: ${{ secrets.GHCR_TOKEN }}
          args: |
            - path: .github/workflows/Dockerfile
              branch: main
              only_changed: true
              with_branch_name: true
              with_timestamp: true
              with_commit_sha: true
