name: 'test to publish docker image'

on:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: 'test'
        uses: kengo-k/docker-build@main
        with:
          token: ${{ secrets.GHCR_TOKEN }}
          timezone: 'Asia/Tokyo'
          args: |
            - path: .github/workflows/Dockerfile
              name: helloworld
              on_branch_changed: false
              on_branch_pushed: true
              on_tag_pushed: true
              include_branch_name: true
              include_timestamp: true
              include_commit_sha: true
